# Generated by Django 5.1.3 on 2024-11-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_visualizer', '0002_mlprediction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlprediction',
            name='visualization',
            field=models.TextField(blank=True, null=True),
        ),
    ]
